apiVersion: v1
kind: cypress
# rootDir: packages/cypress
# defaults:
#   timeout: 15m
sauce:
  region: eu-central-1
  concurrency: 10
  # retries: 2
  metadata:
    tags:
      - e2e
      - release team
cypress:
  version: 13.13.3
  # configFile: saucelab_e2e.config.ts
  configFile: cypress.config.ts

suites:
  - name: 'Chrome on Windows 11'
    browser: 'chrome'
    platformName: 'Windows 11'
    screenResolution: '1440x900'
    # shard: spec
    # smartRetry:
    #   failedOnly: true
    config:
      specPattern: ['cypress/e2e/**/*.feature']

artifacts:
  download:
    when: always
    match:
      - '*'
    directory: ./artifacts/
