apiVersion: v1
kind: cypress
# rootDir: packages/cypress
# defaults:
#   timeout: 15m
sauce:
  region: eu-central-1
  concurrency: 10
  # retries: 2
  metadata:
    tags:
      - e2e
      - release team
cypress:
  version: 13.13.3
  # configFile: saucelab_e2e.config.ts
  configFile: cypress.config.ts

suites:
  - name: 'Chrome on Windows 11'
    browser: 'chrome'
    platformName: 'Windows 11'
    screenResolution: '1440x900'
    # shard: spec
    # smartRetry:
    #   failedOnly: true
    config:
      specPattern: ['cypress/e2e/**/*.feature']

npm:
  packages:
    "@badeball/cypress-cucumber-preprocessor": "^20.0.6"
    "@bahmutov/cypress-esbuild-preprocessor": "^2.2.1"
    "@testing-library/cypress": "^10.0.2"
    "axe-core": "4.9.1"
    "cypress-axe": "^1.5.0"
    "cypress-plugin-tab": "^1.0.5"
    "cypress-real-events": "^1.12.0"
    "cypress-split": "^1.23.0"
    "cypress-wait-until": "^3.0.1"
    "faker": "^5.5.3"
    "fast-xml-parser": "^4.2.4"
    "http-proxy-agent": "^7.0.2"
    "robots-txt-parser": "^1.0.10"
    "@faker-js/faker": "^8.4.1"
    "@types/aria-query": "4.2.2"
    "aria-query": "^4.2.2"
    "cross-env": "^7.0.3"
    "cypress": "^13.12.0"
    "ejs": "3.1.10"
    "esbuild": "^0.20.2"
    "typescript": "^5.3.0"

artifacts:
  download:
    when: always
    match:
      - '*'
    directory: ./artifacts/
